# .classroom.yml
assignments:
  - id: step-03-validation
    grading:
      tests:
        - name: Empty form shows error
          run: php tests/Step3ValidationTest.php --filter testEmptyFormShowsError
          points: 10
        - name: Valid form accepts data
          run: php tests/Step3ValidationTest.php --filter testValidFormAcceptsData
          points: 10
